source 'https://rubygems.org'

gem 'capybara'
gem 'ci_reporter_rspec'
gem 'colorize'
gem 'concurrent-ruby'
gem 'dse-driver'
gem 'dotenv'
gem 'faker'
gem 'json'
gem 'json-compare'
gem 'lois'
gem 'mailinator'
gem 'mongo'
gem 'net-sftp'
gem 'oauth2'
gem 'parallel_rspec'
gem 'parallel_tests'
gem 'pry'
gem 'pry-rescue'
gem 'pry-stack_explorer'
gem 'rainbow', '2.1'
gem 'rake'
gem 'require_all'
gem 'rest-client'
gem 'rspec'
gem 'rspec-rails'
gem 'rspec-retry'
gem 'rubocop'
gem 'rubocop-rspec'
gem 'ruby-kafka', '0.4.3'
gem 'selenium-webdriver'
gem 'vcr'
